spring:
  profiles:
    active:
    - dog
    - EN
    - prod
fake:
  username: YmlUsername
  password: YmlPassword
  jdbcurl: YmlDbUrl

---
spring:
  profiles: prod
fake:
  username: ProdYmlUsername
  password: ProdYmlPassword
  jdbcurl: ProdYmlDbUrl